server:
  port: 8080

spring:
  application:
    name: central
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: usuarios-service
          uri: lb://usuarios-service
          predicates:
            - Path=/api/auth/**

        - id: donaciones-service
          uri: lb://donaciones-service
          predicates:
            - Path=/api/donaciones/**
          filters:
            - JwtAuthenticationFilter
            - name: CircuitBreaker
              args:
                name: donacionesCircuitBreaker
                fallbackUri: forward:/fallback/donaciones

        - id: logistica-service
          uri: lb://logistica-service
          predicates:
            - Path=/api/logistica/**
          filters:
            - JwtAuthenticationFilter
            - name: CircuitBreaker
              args:
                name: logisticaCircuitBreaker
                fallbackUri: forward:/fallback/logistica

        - id: necesidades-service
          uri: lb://necesidades-service
          predicates:
            - Path=/api/necesidades/**
          filters:
            - JwtAuthenticationFilter
            - name: CircuitBreaker
              args:
                name: necesidadesCircuitBreaker
                fallbackUri: forward:/fallback/necesidades

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10 # ultimas 10 peticiones que entraron
        permittedNumberOfCallsInHalfOpenState: 3 #cuantas peticiones se permiten en estado medio abierto
        failureRateThreshold: 50 #si falla el 50% de las peticiones el servidor deja de funcionar para que no caigan otros servidores y da el error 
        waitDurationInOpenState: 10000 #tiempo en estado abierto
    instances:
      donacionesCircuitBreaker:
        baseConfig: default
      logisticaCircuitBreaker:
        baseConfig: default
      necesidadesCircuitBreaker:
        baseConfig: default
