# Puerto asignado para este microservicio
spring.application.name=necesidades-service
server.port=8083

# ============================================================
# Configuración de Base de Datos PostgreSQL
# ============================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/necesidades_db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=donaton
spring.datasource.password=donaton123

# Hibernate creará las tablas automáticamente basado en las Entidades
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Ver las sentencias SQL generadas por Hibernate en consola
spring.jpa.show-sql=true

# Eureka Config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.preferIpAddress=true
